resources:
  - name: beginner
    type: git
    source: &repo-source
      uri: https://github.com/jellytw/beginner.git
      branch: master
jobs:
  - name: Run tests
    plan:
      - get: beginner
        trigger: true
      - task: run the palindrome logic
        file: beginner/ci/tasks/run_tests.yml
